name: Create and publish a Docker image

on:
  push:
    branches:
    - 'master'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  run-tests:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      # debug
      - run: |
          echo "This job was triggered by this event: ${{ github.event_name }}"
          echo "This job is running on ${{ runner.os }}"
          echo "The name of your repository is ${{ github.repository }}"
          echo "ref_name env var is '$GITHUB_REF_NAME' and the tag name is '${{ github.ref_name }}'"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Run tests
        run: go mod tidy && go test -v ./...
